CREATE SCHEMA CW1
GO

CREATE TABLE CW1.Users (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL
);
GO


CREATE TABLE CW1.Trail (
    TrailID INT IDENTITY(1,1) PRIMARY KEY,
    TrailName VARCHAR(255) NOT NULL,
    Location VARCHAR(255),
    Difficulty VARCHAR(50),
    Description TEXT
);
GO

CREATE TABLE CW1.Activity (
    ActivityID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL FOREIGN KEY REFERENCES CW1.Users(UserID),
    ActivityType VARCHAR(100) NOT NULL,
    Duration DECIMAL(5,2),
    Distance DECIMAL(6,2)
);
GO

CREATE TABLE CW1.Review (
    ReviewID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL FOREIGN KEY REFERENCES CW1.Users(UserID),
    TrailID INT NOT NULL FOREIGN KEY REFERENCES CW1.Trail(TrailID),
    Rating TINYINT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    ReviewText TEXT
);
GO
